name: Search SMILES pattern

on:
  discussion:
    types: [labeled]
  discussion_comment:
    types: [created]

defaults:
  run:
    shell: bash -l {0}

jobs:
  search-smiles:
    # only run if body contains 'botsearch' and not 'norun'
    # if: ${{ contains(github.event.comment.body, 'botsearch') && !contains(github.event.comment.body, 'norun') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/openff-env.yaml
          create-args: >-
            python=3.11

      - name: Environment Information
        run: |
          conda info
          conda list

      - name: Search SMILES pattern
        run: |
          BASE_COMMAND=$(                                 \
            python scripts/parse-comment-for-search.py    \
            --text '${{ github.event.comment.body }}${{ github.event.discussion.body }}'     \
          )
          COMMAND=$(              \
            echo $BASE_COMMAND    \
              --discussion-number ${{ github.event.discussion.number }} \
              --output-directory artifact             \
              --workflow-run-id ${{ github.run_id }}  \
              --combinations-directory combinations   \
            )

          echo $COMMAND
          eval $COMMAND

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifact
          retention-days: 7
